# Basic configuration for an ESP32 device
esphome:
  name: makepico1
  friendly_name: makepico1

# Hardware configuration
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:
  platform: esphome
  password: "Qwerdsatedirdsw32"

# Connect to WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot if WiFi connection fails
  ap:
    ssid: "makepico1 Fallback Hotspot"
    password: "qsR3P9t0zmoE"

# Enable web server
web_server:

status_led:
  pin: GPIO22

switch:
  - platform: gpio
    name: "LED 21"
    pin: GPIO21

  - platform: template
    name: "LCD Backlight"
    id: backlight_switch
    lambda: return id(backlight_switch).state;
    turn_on_action:
      - lambda: |-
          id(mydisplay).backlight();
          id(backlight_switch).state = true;
    turn_off_action:
      - lambda: |-
            id(mydisplay).no_backlight();
            id(backlight_switch).state = false;

i2c:
  - id: bus_a
    sda: GPIO26
    scl: GPIO25
    scan: true

display:
  - id: mydisplay
    platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    lambda: |-
      it.print("Hello World!");


captive_portal:
    