esphome:
  name: ag151
  friendly_name: ag151

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ieApSaJ2Szkq7+hwRFAUIbE6nPceJM87jvLL41nIJ+0="

ota:
  - platform: esphome
    password: "2f1faecb8f4d574671375864973b78dc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ag151 Fallback Hotspot"
    password: "qsR3P9t0zmoE"

status_led:
  pin: GPIO2

switch:
  - platform: gpio
    name: "LED 0"
    pin: GPIO0

  - platform: gpio
    name: "LED 5"
    pin: GPIO5

  - platform: gpio
    name: "LED 15"
    pin: GPIO15

  - platform: gpio
    name: "LED 13"
    pin: GPIO13
  
  - platform: gpio
    name: "LED 12"
    pin: GPIO12
  
  - platform: gpio
    name: "LED 14"
    pin: GPIO14

  - platform: gpio
    name: "LED 16"
    pin: GPIO16

sensor:
  - platform: dht
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

captive_portal:
    